# Generated by Django 4.1.4 on 2022-12-15 18:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Purchase', '0006_alter_orders_ordereddate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='OrderedDate',
            field=models.DateField(default=datetime.datetime(2022, 12, 15, 10, 21, 13, 383687)),
        ),
        migrations.AlterField(
            model_name='vendororder',
            name='Ordereddate',
            field=models.DateField(default=datetime.datetime(2022, 12, 15, 10, 21, 13, 386685)),
        ),
    ]
