# Generated by Django 4.0.6 on 2022-12-11 07:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Banking', '0004_alter_credit_amount_date_alter_withdraw_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit_amount',
            name='Date',
            field=models.DateField(default=datetime.datetime(2022, 12, 11, 13, 2, 59, 736100)),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='Date',
            field=models.DateField(default=datetime.datetime(2022, 12, 11, 13, 2, 59, 735099)),
        ),
    ]
