# Generated by Django 4.0.6 on 2022-12-11 07:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0004_alter_salesitem_stock_alter_salesorder_ordereddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='OrderedDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 11, 7, 32, 59, 727101, tzinfo=utc)),
        ),
    ]
